In [9]:
import numpy as np
a=np.array([1,2,3])
print(a[2])
print(a)
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)
print(type(a))
print(a[0,1],a[0,0])

3
[1 2 3]
[[1 2 3]
 [4 5 6]]
2
<class 'numpy.ndarray'>
2 1


In [17]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a[0,-1])
a=np.array([1,2,3,4,5,6])
print(a[2:5])


(2, 3)
3
[3 4 5]


In [18]:
#concatenate
n1=np.array([10,20,30])
n2=np.array([40,50,60])
print(np.concatenate((n1,n2)))

[10 20 30 40 50 60]
